version: "3.4"

services:
  db:
    image: mongo:4.2
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "dev_db_user"
      MONGO_INITDB_ROOT_PASSWORD: "testingisgood"
      MONGO_INITDB_DATABASE: "admin"
